---
- name: "Add Node.js from Source"
  become: true 
  shell: |
    curl --silent --location https://deb.nodesource.com/setup_13..x | sudo -E bash - 

- name: "Install Node JS 13"
  become: true
  apt:
    name: ["node-js"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "Move env variables to /etc/profile.d/"
  become: true 
  copy:
    scr: myenv.sh
    dest: /etc/profile.d/

    